package com.cnh.dataobject;

import java.util.Date;

public class SuccessKilledDo {
   
	 /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column success_killed.seckill_id
    *
    * @mbg.generated Sat May 18 15:54:34 CST 2019
    */
   private Long seckillId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column success_killed.user_phone
    *
    * @mbg.generated Sat May 18 15:54:34 CST 2019
    */
   private String userPhone;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column success_killed.seckill_id
    *
    * @return the value of success_killed.seckill_id
    *
    * @mbg.generated Sat May 18 15:54:34 CST 2019
    */
   public Long getSeckillId() {
       return seckillId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column success_killed.seckill_id
    *
    * @param seckillId the value for success_killed.seckill_id
    *
    * @mbg.generated Sat May 18 15:54:34 CST 2019
    */
   public void setSeckillId(Long seckillId) {
       this.seckillId = seckillId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column success_killed.user_phone
    *
    * @return the value of success_killed.user_phone
    *
    * @mbg.generated Sat May 18 15:54:34 CST 2019
    */
   public String getUserPhone() {
       return userPhone;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column success_killed.user_phone
    *
    * @param userPhone the value for success_killed.user_phone
    *
    * @mbg.generated Sat May 18 15:54:34 CST 2019
    */
   public void setUserPhone(String userPhone) {
       this.userPhone = userPhone == null ? null : userPhone.trim();
   }
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.state
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.creat_time
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    private Date creatTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.state
     *
     * @return the value of success_killed.state
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.state
     *
     * @param state the value for success_killed.state
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.creat_time
     *
     * @return the value of success_killed.creat_time
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.creat_time
     *
     * @param creatTime the value for success_killed.creat_time
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }
}