package com.cnh.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cnh.dataobject.SeckillDo;

public interface SeckillDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int deleteByPrimaryKey(Long seckillId);
    
    
    /*
    减库存,根据商品id和秒杀下单时间
    其实就是update语句。库存减一，如果影响行数=1，表示已经更新了，如果为0，就表示没有修改
    如果>1就表示更新的行数
     */
    int reduceNumber(@Param("seckillId")long seckillId,@Param("killTime")Date killTime);
    /*
     * 根据偏移量查询秒杀商品列表
     */
    List<SeckillDo>queryAll (@Param("offset")int offset,@Param("limit")int limit);
    
    
    void killByProcedure(Map<String,Object> paramMap);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int insert(SeckillDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int insertSelective(SeckillDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    SeckillDo selectByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int updateByPrimaryKeySelective(SeckillDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int updateByPrimaryKey(SeckillDo record);
}