package com.cnh.dao;

import java.util.Date;

import org.apache.ibatis.annotations.Param;

import com.cnh.dataobject.SuccessKilledDo;


public interface SuccessKilledDoMapper {
	 /*
    插入购买明细，可重复过滤（mysql设置了联合主键，防止某些人刷单）
     */
    int insertSuccessKilled(@Param("seckillId")long seckillId,@Param("userPhone")long userPhone);


/*
根据id查询successkilled 并携带秒杀产品对象实体，
返回的是successDo这个对象，但是这个对象又包括了seckilled
这里使用了内连接。记在笔记本上了
 */

 SuccessKilledDo queryByIdWithSeckill(@Param("seckillId")long seckillId,@Param("userPhone")long userPhone);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int insert(SuccessKilledDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int insertSelective(SuccessKilledDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int updateByPrimaryKeySelective(SuccessKilledDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int updateByPrimaryKey(SuccessKilledDo record);
}