package com.cnh.dao;

import com.cnh.dataobject.UserInfoDo;

public interface UserInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int insert(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int insertSelective(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    UserInfoDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int updateByPrimaryKeySelective(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat May 18 15:54:34 CST 2019
     */
    int updateByPrimaryKey(UserInfoDo record);
}